### ISSUE TITLE
关于教务系统成绩查询地址的获取

### ISSUE THREAD

**Issue by sasaju** [SukiEva/Myhhu#1]
本人学校使用的教务系统该界面无法查询，点击之后会报405错误
![image](https://user-images.githubusercontent.com/21136684/111071403-fb7a4f80-8510-11eb-9540-295ba7439779.png)
想询问一下作者学校的教务系统是否可以使用该界面

另外，想问一下作者，这两个网址是在访问哪个页面下抓取到的"student/integratedQuery/scoreQuery/schemeScores/callback"（成绩查询）、"student/integratedQuery/gpaRankingQuery/index/jdpmcx"（绩点查询），我访问很多页面也没有在开发者工具里抓取到对应的网址
提前感谢作者😋

**Comment by SukiEva** [comment]
查询成绩在综合查询里面，那两个网址分别点击方案成绩和学生绩点查询可以获得

![image](https://user-images.githubusercontent.com/43002076/111120396-409c9100-85a6-11eb-9762-6a34b9709f00.png)

**Comment by sasaju** [comment]
> 查询成绩在综合查询里面，那两个网址分别点击方案成绩和学生绩点查询可以获得
> 
> ![image](https://user-images.githubusercontent.com/43002076/111120396-409c9100-85a6-11eb-9762-6a34b9709f00.png)
哦好的 谢谢作者，看来虽然同为新版urp但不同学校不同配置，我们学校的教务系统并没有这两个选项，可以提供一下这两个选项点击之后跳转的网址吗，我想看看是否可以通过直接访问来查看这两个页面

**Comment by SukiEva** [comment]
方案成绩：/student/integratedQuery/scoreQuery/schemeScores/index
学生绩点：/student/integratedQuery/gpaRankingQuery/index
虽然不知道有什么不同，不过我这考务管理里查的一般是计算机等级考试成绩之类，课程成绩都在综合查询里面

**Comment by sasaju** [comment]
> 方案成绩：/student/integratedQuery/scoreQuery/schemeScores/index
> 学生绩点：/student/integratedQuery/gpaRankingQuery/index
> 虽然不知道有什么不同，不过我这考务管理里查的一般是计算机等级考试成绩之类，课程成绩都在综合查询里面

我们的综合查询只有这些内容，压根就没有成绩查询，我们平时查成绩一般是通过公众号和易班
![image](https://user-images.githubusercontent.com/21136684/111122131-8eb29400-85a8-11eb-84e0-57207eaefb98.png)
计算机等级考试和四六级之类放在了培养方案完成情况里

**Comment by SukiEva** [comment]
那就不清楚了😂如果教务系统找不到，可以考虑用抓包app从安卓端找

**Comment by sasaju** [comment]
> 那就不清楚了😂如果教务系统找不到，可以考虑用抓包app从安卓端找

哈哈哈  我们的教务系统可以打开第一个网址，第二个会报404，不过我很高兴了哈哈哈哈
