### ISSUE TITLE
新门户bug

### ISSUE THREAD

**Issue by katezero000** [SukiEva/Myhhu#3]
打卡自动填写和信息门户打开登录后会闪回统一身份认证，不知道是不是新门户的问题？

**Comment by SukiEva** [comment]
学校更新了信息门户，改了网址，我需要更新一下

**Comment by SukiEva** [comment]
> 打卡自动填写和信息门户打开登录后会闪回统一身份认证，不知道是不是新门户的问题？

新版打开有未知bug，已经修改为旧版信息门户地址
